version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "parquimetro_db"
    ports:
      - "15432:5432"
    networks:
      - postgres-compose-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network
  parkingapp:
    build:
      context: .
    container_name: parkingapp
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/parquimetro_db"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "root"
    networks:
      - postgres-compose-network

volumes:
  postgres-data:

networks:
  postgres-compose-network:
    driver: bridge